{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quan.api",
    "module": "api-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-utils-1.0.0.jar",
          "url": "api-utils-1.0.0.jar",
          "size": 11163,
          "sha512": "7102df29b2727b2cad32c55166aae3840634f738939bea8117a511fdc2cda305d18e6432d5ba61e4fd3ce8f6c825d57ca6ffe53055db4e9bc0a6c0e171932959",
          "sha256": "fa5fbc249b792d3d4cea10c6d2bfcadc5be9b559a61e4e82f047f594112df6ed",
          "sha1": "50411631b104be7d3b788991794cb52c47131c35",
          "md5": "df449e71cfea13c2b5df962bf753ea9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "api-utils-1.0.0.jar",
          "url": "api-utils-1.0.0.jar",
          "size": 11163,
          "sha512": "7102df29b2727b2cad32c55166aae3840634f738939bea8117a511fdc2cda305d18e6432d5ba61e4fd3ce8f6c825d57ca6ffe53055db4e9bc0a6c0e171932959",
          "sha256": "fa5fbc249b792d3d4cea10c6d2bfcadc5be9b559a61e4e82f047f594112df6ed",
          "sha1": "50411631b104be7d3b788991794cb52c47131c35",
          "md5": "df449e71cfea13c2b5df962bf753ea9b"
        }
      ]
    }
  ]
}
